FROM node:22-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Copiar entrypoint
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 4321
EXPOSE 8787

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["sh", "-c", "npm run dev & npx wrangler dev --local --port 8787"]

